//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "asegurado")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Option<Uuid>,
    #[sea_orm(column_type = "Text")]
    pub natural_id: String,
    #[sea_orm(column_type = "Text")]
    pub nombre_aseguradora: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cita::Entity")]
    Cita,
    #[sea_orm(
        belongs_to = "super::patient::Entity",
        from = "Column::UserId",
        to = "super::patient::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    Patient,
}

impl Related<super::cita::Entity> for Entity {
    fn to() -> RelationDef { Relation::Cita.def() }
}

impl Related<super::patient::Entity> for Entity {
    fn to() -> RelationDef { Relation::Patient.def() }
}

impl ActiveModelBehavior for ActiveModel {}
