//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cita")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub doctor_id: Option<Uuid>,
    pub paciente_id: Option<Uuid>,
    pub asegurado_id: Option<Uuid>,
    pub fecha: DateTime,
    pub timestamp_end: Option<DateTime>,
    pub estado: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::asegurado::Entity",
        from = "Column::AseguradoId",
        to = "super::asegurado::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    Asegurado,
    #[sea_orm(
        belongs_to = "super::doctor::Entity",
        from = "Column::DoctorId",
        to = "super::doctor::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    Doctor,
    #[sea_orm(
        belongs_to = "super::patient::Entity",
        from = "Column::PacienteId",
        to = "super::patient::Column::Id",
        on_update = "Restrict",
        on_delete = "SetNull"
    )]
    Patient,
}

impl Related<super::asegurado::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Asegurado.def()
    }
}

impl Related<super::doctor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Doctor.def()
    }
}

impl Related<super::patient::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patient.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
