//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "doctor_especialidad")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub doctor_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub especialidad_id: i16,
    pub certification_date: Option<Date>,
    pub activo: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::doctor::Entity",
        from = "Column::DoctorId",
        to = "super::doctor::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Doctor,
    #[sea_orm(
        belongs_to = "super::especialidad::Entity",
        from = "Column::EspecialidadId",
        to = "super::especialidad::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Especialidad,
}

impl Related<super::doctor::Entity> for Entity {
    fn to() -> RelationDef { Relation::Doctor.def() }
}

impl Related<super::especialidad::Entity> for Entity {
    fn to() -> RelationDef { Relation::Especialidad.def() }
}

impl ActiveModelBehavior for ActiveModel {}
