//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "especialidad")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i16,
    #[sea_orm(column_type = "Text", unique)]
    pub nombre: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub img_path: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::doctor_especialidad::Entity")]
    DoctorEspecialidad,
}

impl Related<super::doctor_especialidad::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DoctorEspecialidad.def()
    }
}

impl Related<super::doctor::Entity> for Entity {
    fn to() -> RelationDef {
        super::doctor_especialidad::Relation::Doctor.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::doctor_especialidad::Relation::Especialidad.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
