//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

pub use super::asegurado::Entity as Asegurado;
pub use super::cita::Entity as Cita;
pub use super::doctor::Entity as Doctor;
pub use super::doctor_especialidad::Entity as DoctorEspecialidad;
pub use super::especialidad::Entity as Especialidad;
pub use super::habitacion::Entity as Habitacion;
pub use super::patient::Entity as Patient;
pub use super::user::Entity as User;
