//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub cedula: String,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub passport: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::asegurado::Entity")]
    Asegurado,
    #[sea_orm(has_one = "super::doctor::Entity")]
    Doctor,
    #[sea_orm(has_one = "super::patient::Entity")]
    Patient,
}

impl Related<super::asegurado::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Asegurado.def()
    }
}

impl Related<super::doctor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Doctor.def()
    }
}

impl Related<super::patient::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patient.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
